config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :goat_ads do
    resources :bookings, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :goat_ad
  belongs_to :user
end

app/models/goat_ad.rb
class GoatAd < ApplicationRecord
  has_many :bookings
  belongs_to :user
  has_many_attached :medias

  validates :name, :age, :description,
            :price_per_day, :features, presence: true
  validates :name, length: { minimum: 2 }
  validates :description, length: { minimum: 20 }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_and_features,
                  against: %i[name features address],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :goat_ads
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  # def new
  #   @booking = Booking.new
  # end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @goat_ad = GoatAd.find(params[:goat_ad_id])
    @booking.goat_ad = @goat_ad
    @booking.user_id = current_user.id

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { redirect_to goat_ad_path(@goat_ad.id), alert: "error message" }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_booking
    @booking = Booking.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def booking_params
    params.require(:booking).permit(:name, :start_time, :end_time)
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
end

app/controllers/goat_ads_controller.rb
class GoatAdsController < ApplicationController
  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR features ILIKE :query OR address ILIKE :query"
      @goat_ads = GoatAd.where(sql_query, query: "%#{params[:query]}%")
    elsif params[:feature].present?
      @feature = params[:feature]
      @goat_ads = GoatAd.where(features: @feature)
    else
      @goat_ads = GoatAd.all
    end
    @markers = @goat_ads.geocoded.map do |goat_ad|
      {
        lat: goat_ad.latitude,
        lng: goat_ad.longitude
      }
    end
  end

  def show
    @goat_ad = GoatAd.find(params[:id])
    @booking = Booking.new
  end

  def new
    @goat_ad = GoatAd.new
  end

  def create
    @goat_ad = GoatAd.new(goat_ad_params)
    @goat_ad.user_id = current_user.id
    if @goat_ad.save!
      redirect_to goat_ad_path(@goat_ad)
    else
      render :new
    end
  end

  def edit
    @goat_ad = GoatAd.find(params[:id])
  end

  def update
    @goat_ad = GoatAd.find(params[:id])
    @goat_ad.update(goat_ad_params)
    redirect_to goat_ad_path(@goat_ad)
  end

  def destroy
    @goat_ad = GoatAd.find(params[:id])
    @goat_ad.destroy
    redirect_to goat_ads_path
  end

  private

  def goat_ad_params
    params.require(:goat_ad).permit(:id, :name, :age, :address, :latitude, :longitude, :description, :price_per_day,
                                    :features, :start_available, :end_available, medias: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @goat_ads = GoatAd.all
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def features_collection
    %w[fighter milker mower sociable space-traveller]
  end

  def fighter
    "fighter"
  end

  def milker
    "milker"
  end

  def sociable
    "sociable"
  end

  def mower
    "mower"
  end

  def space_traveller
    "space-traveller"
  end
end

app/views/bookings/_form.html.erb
<%= simple_form_for(@booking) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :start_time %>
    <%= f.input :end_time %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>
<div class="bookings-container-box">
  <h1>All my bookings 🐐</h1>

<div class="cards">

<% @bookings.each do |booking| %>>

 <div class="card">
                    <div class="card-image">
                      <%= cl_image_tag booking.goat_ad.medias.first.key, height: 200, width: 200, crop: :fill%>
                    </div><br/>
                  <div class="card-info">
                    <h4><%= booking.name %></h4>
                    <h5><%= booking.goat_ad.name %></h5>
                    <p><%= booking.start_time %></p>
                    <p><%= booking.end_time %></p>
                    <%# <td><%= link_to booking_path(booking) do %>
                    <%# <i class="far fa-eye"></i> %>
                    <%# <% end %></td>
                    <td><%= link_to edit_booking_path(booking) do %>
                    <i class="far fa-edit"></i>
                    <% end %></td>
                    <%# <td><%= link_to booking_path(booking) method: :delete, data: { confirm: 'Are you sure?' } %>
                    <%# <i class="far fa-edit"></i> %>
                    <%# <% end %></td>
                  </div>
                </div>
    <% end %>
    <br>
  </div>
</div>

<%# <%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @booking.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @booking.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @booking.end_time %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/goat_ads/index.html.erb
    <div class="container_card">
        <div class="content">
        <h1>Category : <%= @feature %> </h1>
          <div class="cards">
              <% @goat_ads.each do |goat_ad| %>
              <%= link_to goat_ad_path(goat_ad), class: "text-decoration-none" do %>

                <div class="card">
                  <div class="card-image">
                    <% goat_ad.medias.first(1).each do |media| %>
                    <%= cl_image_tag media.key, height: 200, width: 200, crop: :fill%>
                    <% end %>
                  </div>
                  <div class="card-info">
                    <h3><%= goat_ad.name %></h3>
                    <p><%= goat_ad.description %></p>
                    <p><span><%= goat_ad.price_per_day %>€/day </span></p>
                  </div>
                </div>
            <% end %>
            <% end %>
        </div>
      </div>
    <div id="map"
     style="width: 60%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

app/views/goat_ads/new.html.erb
<div class="new">

<%= simple_form_for [ @goat_ad] do |f| %>
  <%= f.input :name %>
  <%= f.input :age %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_day %>
  <%= f.input :features, :collection => %w[fighter milker mower sociable space-traveller] %>
  <%= f.input :medias, as: :file, input_html: { multiple: true }, label: "Add a media of your goat" %>
  <%= f.input :start_available %>
  <%= f.input :end_available %>

 <div class="btn"> <%= f.submit "Submit creation", class: "btn btn-primary" %> </div>

<% end %>

<div class="btn"> <%= link_to "Back", root_path, class: "btn" %> </div>

</div>

<div class="footer">
  <h6>© 2021 Team Oukilé, Inc.</h6>
</div>

app/views/goat_ads/show.html.erb
<div class="goat-header">
  <div class="container-box-4">
    <%= link_to "Home", root_path, class: "text-decoration-none"%> > <%=link_to @goat_ad.features, goat_ads_path , class: "text-decoration-none" %> > <%= @goat_ad.name %>
    <h1><%= @goat_ad.name %></h1>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i> <p> (25 reviews)</p>
    </div>
</div>

<div class="container-box-4">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= cl_image_tag @goat_ad.medias[0].key, :width=>250, :height=>350, crop: :fit, class: "d-block w-100" %>
      </div>
      <% @goat_ad.medias.each_with_index do |media, index| %>
      <% if index > 0 %>
      <div class="carousel-item">
        <%= cl_image_tag media.key, :width=>250, :height=>350,crop: :fit, class: "d-block w-100" %>
      </div>
      <% end %>
    <% end %>
    </div>

    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  </br>

  <div class="galleryflex">
    <% @goat_ad.medias.each do |media| %>
    <div class="gallery_show">
      <%= cl_image_tag media.key, height: 110, width: 195, crop: :fill %>
    </div>
    <% end %>

  </div>
</div>

<div class="container-box-flex">
  <div class="goat-board">
      <h4>Single goat. Owner: <%= @goat_ad.user.first_name %></h4>
        <p><i class="fas fa-birthday-cake" width="20px"></i> <%= @goat_ad.age %> years old</p>
        <p><i class="far fa-dot-circle"></i> <%= @goat_ad.features %></p>
      <hr class="solid">
      <div class="goat-description">
        <h4>Description</h4>
        <p><%= @goat_ad.description %></p>
      </div>
  </div>

  <div class="booking-card" style="width: 22rem;">
      <div class="card-body">
        <h5 class="booking-card-price"><%= @goat_ad.price_per_day %>€ /day</h5>
        <%= simple_form_for [ @goat_ad, @booking ] do |f| %>
          <%= f.input :start_time, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.input :end_time, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.button :submit, "Book now", class: "btn btn-dark btn-block" %>
        <% end %>
    </div>
</div>



  <%#=    <h2> <%= @goat_ad.name %> </h2>
  <%#=     <p> <%= @goat_ad.age %> </p>
  <%#=     <p> <%= @goat_ad.address %> </p>
  <%#=     <p> <%= @goat_ad.longitude %> </p>
  <%#=    <p> <%= @goat_ad.latitude %> </p>
  <%#=     <p> <%= @goat_ad.description %> </p>
  <%#=     <p> <%= @goat_ad.price_per_day %> </p>
  <%#=     <p> <%= @goat_ad.features %> </p>
  <%#=     <p> <%= @goat_ad.medias %> </p>
  <%#=     <p> <%= @goat_ad.start_available %> </p>
  <%#=     <p> <%= @goat_ad.end_available %> </p>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
    <title>BoucIng</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  <%= render 'shared/footer'%>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container-box1">
  <h1>Get your goat </h1>
  <h2>      & got your guest</h2>
    <div class="form">
              <%= form_tag goat_ads_path, method: :get,
                class: "formsearch" do %>
              <%= text_field_tag :query,
                params[:query],
                class: "search_bar",
                placeholder: "Find a goat"
              %>
            </li>
             <%= submit_tag "Search", class: "btn btn-dark" %>
            <% end %>
    </div>
  </div>
  <div class="container-box2">
  <img src="https://lh3.googleusercontent.com/proxy/_ACMiypmng0KOfLJCX4DihkWtz5-qc6PXcCoC4iyEXOBb5ZUN2GQyRHFcWbQ_4v45WLbKEd2A9inBs1T80aePJSQShSUDh3_9maMw8WrNH5jBw" alt="">
  </div>
</div>

<br>
<br>
<div class="container-box">
<h3>Top categories</h3>
<br>
 <p>Goats are specialized professionnals - Find the one you need !</p>

<div class="cards1">
     <div class="card-category" style="background-image: url(https://images.unsplash.com/photo-1613846043689-afad9cb6317d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1052&q=80)"> <%= link_to "fighter", goat_ads_path(feature: fighter), class: "text-decoration-none" %></div>
     <div class="card-category" style="background-image: url(https://images.unsplash.com/photo-1602153508683-b5bc610271d6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80)"> <%= link_to "milker", goat_ads_path(feature: milker), class: "text-decoration-none" %></div>
     <div class="card-category" style="background-image: url(https://images.unsplash.com/photo-1567017497423-2de680cc04b2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80)"> <%= link_to "mower", goat_ads_path(feature: mower), class: "text-decoration-none" %></div>
     <div class="card-category" style="background-image: url(https://images.unsplash.com/photo-1603602943247-93dc0c81a932?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80)"> <%= link_to "sociable", goat_ads_path(feature: sociable), class: "text-decoration-none" %></div>
     <div class="card-category" style="background-image: url(https://images.unsplash.com/photo-1614728263952-84ea256f9679?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1469&q=80)"> <%= link_to "space-traveller", goat_ads_path(feature: space_traveller), class: "text-decoration-none" %></div>

 </div>

</div>

<div class="container-box">
<h3>Goats of the month</h3>
<br>
<p>Elected by our customers, the bests of the bests !</p>
<div class="cards">

<% @goat_ads.each do |goat_ad| %>

 <div class="card" style="width: 22rem;">


    <div class="card-img-top">
      <%= link_to goat_ad do %>
      <% goat_ad.medias.first(1).each do |media| %>
      <%= cl_image_tag media.key, height: 200, width: 200, crop: :fit%>
      <% end %>

      <% end %>
    </div>

    <div class="card-body">
        <h5 class="card-title"><%= goat_ad.name %></h5>
        <p class="card-text"><%=goat_ad.features%></p>
        <p class="card-info"><span><%=goat_ad.price_per_day%> €/day</span></p>
        <%= link_to "Rent now", goat_ad , class: "btn btn-dark" %>
    </div>


  </div>
    <% end %>
 </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="footer-links">
    <a href="https://github.com/clemcheyrou/BoucIng"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/world_goats/?hl=fr"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/groups/720464345102058"><i class="fab fa-facebook"></i></a>

  </div>

  <div class="footer-copyright">
    <strong>Boucing ©</strong> - This footer is goat's friendly
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="brand d-flex p-2">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://theme.zdassets.com/theme_assets/1318471/b1cf7965b65dbf1abc4e18e553f7f943c50fea5c.png" %>
    <% end %>
    <h4>Boucing</h4>
  </div>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
            <li class="nav-item search">
            <%= form_tag goat_ads_path, method: :get,
                class: "formsearch" do %>
              <%= text_field_tag :query,
                params[:query],
                class: "search_bar",
                placeholder: "Find a goat"
              %>
            </li>
             <%= submit_tag "Search", class: "btn btn-dark" %>
            <% end %>
          </li>
          </div>
        <li class="nav-item dropdown">
        <li class="current"><%= link_to "Rent your goat", new_goat_ad_path %> </li>
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
         <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit my profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "View my bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
      <li class="nav-item">
          <input type="text" class="search_bar" placeholder="Search..">
      </li>
      <li class="nav-item">
          <li class="current"><%= link_to "Rent your goat", new_goat_ad_path %></li>
      </li>
      <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>

      <% end %>
    </ul>
  </div>
</div>